Learning Numpy


What is numpy?


NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

In [ ]:
import numpy as np

a=np.arange(10)
a.shape

(10,)

In [ ]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# What’s the difference between a Python list and a NumPy array?

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

In [ ]:
#One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.
a=np.array([1,9,4,5,6,7])
b=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(a)
print(b)

[1 9 4 5 6 7]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


 The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

## Vector
 A vector is an array with a single dimension
## Matrix
 matrix refers to an array with two dimensions
## Tensor
 For 3-D or higher dimensional arrays, the term tensor is also commonly used.

In [ ]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(2,int)

array([0, 0])

In [ ]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(3,str)

array(['1', '1', '1'], dtype='<U1')

In [ ]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

 array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.

In [ ]:
np.arange(1,10,3)

array([1, 4, 7])

## np.linspace-array with values that are spaced linearly in a specified interval:ection

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.linspace(2,5,8)

array([2.        , 2.42857143, 2.85714286, 3.28571429, 3.71428571,
       4.14285714, 4.57142857, 5.        ])

In [ ]:
np.array([1, 4, 2, '5', 3])

array(['1', '4', '2', '5', '3'], dtype='<U21')

In [ ]:
a= np.array([7,8.9,2,8.0])

In [ ]:
np.sort(a)

array([2. , 7. , 8. , 8.9])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a=np.array([[8,9]])
b=np.array([[7,0],[4,9]])


In [ ]:
np.concatenate((b,a), axis=0)

array([[7, 0],
       [4, 9],
       [8, 9]])

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [ ]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [ ]:
#Checking the dimension
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
five_up = (a >= 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [ ]:
# If you want to find the sum of the elements in an array, you’d use sum().
a = np.array([1, 2, 3, 4])

a.sum()

10

In [ ]:
b= np.array([[6,7,8],[7,8,9]])
b.sum(axis=0)

array([13, 15, 17])

In [ ]:
b.sum(axis=1)

array([21, 24])

In [ ]:
a=np.array([8,9,7,9,0,29])
np.unique(a)

array([ 0,  7,  8,  9, 29])

In [ ]:
unique_rows, indices, occurrence_count = np.unique(
     a, axis=0, return_counts=True, return_index=True)
print(indices)

[4 2 0 1 5]


In [ ]:
print(occurrence_count)

[1 1 1 2 1]


In [ ]:
np.flip(a)

array([29,  0,  9,  7,  9,  8])

In [ ]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(4)

array([0.33499492, 0.77630293, 0.98626213, 0.9652312 ])

In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
x.view()

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x.copy()

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
s= x.view()
s[1][2]=34

In [ ]:
s

array([[ 1,  2,  3,  4],
       [ 5,  6, 34,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6, 34,  8],
       [ 9, 10, 11, 12]])

In [ ]:
s=x.ravel()

In [ ]:
s

array([ 1,  2,  3,  4,  5,  6, 34,  8,  9, 10, 11, 12])

In [ ]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6, 34,  8],
       [ 9, 10, 11, 12]])

In [ ]:
e=x.flatten()
e[3]=3
x
e

array([ 1,  2,  3,  3,  5,  6, 34,  8,  9, 10, 11, 12])

In [ ]:
r=x.ravel()
r[5]=987

In [ ]:
x

array([[  1,   2,   3,   4],
       [  5, 987,  34,   8],
       [  9,  10,  11,  12]])

In [ ]:
r

array([  1,   2,   3,   4,   5, 987,  34,   8,   9,  10,  11,  12])

In [ ]:
s=np.random.seed(10)

In [ ]:
s

In [ ]:
np.full(2,7)

array([7, 7])

In [ ]:
np.eye(7,dtype=float)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(34,dtype= float)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
a=([[7,8],[3,4]])
np.linalg.det(a)
np.linalg.inv(a)
np.linalg.eig(a)

(array([10.62347538,  0.37652462]),
 array([[ 0.9109185 , -0.77026256],
        [ 0.41258634,  0.63772689]]))

In [ ]:
b=([9,0],[3,5])
np.dot(a,b)
np.cross(a,b)


array([-72,   3])

In [ ]:
import numpy as np
n = np.arange(15).reshape(5,3)
n[np.where(n>10)]

array([11, 12, 13, 14])

In [ ]:
n

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
np.put(n,[1,2,3],[2,3,4])

In [ ]:
n


array([[ 0,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

AttributeError: ignored

In [ ]:
import numpy as np
import csv

with open ('/content/sample_data/california_housing_test.csv','r') as file:
  r= csv.reader(file)
  data= list(r)

a= np.array(data)

In [ ]:
a

array([['longitude', 'latitude', 'housing_median_age', ..., 'households',
        'median_income', 'median_house_value'],
       ['-122.050000', '37.370000', '27.000000', ..., '606.000000',
        '6.608500', '344700.000000'],
       ['-118.300000', '34.260000', '43.000000', ..., '277.000000',
        '3.599000', '176500.000000'],
       ...,
       ['-119.700000', '36.300000', '10.000000', ..., '220.000000',
        '2.289500', '62000.000000'],
       ['-117.120000', '34.100000', '40.000000', ..., '14.000000',
        '3.270800', '162500.000000'],
       ['-119.630000', '34.420000', '42.000000', ..., '260.000000',
        '8.560800', '500001.000000']], dtype='<U18')

In [ ]:
a1=a[:,0]


In [ ]:
s=a1[1:]

In [ ]:
s.astype(float).mean()

-119.58919999999999

In [ ]:
s.size

3000

In [ ]:
a2=a[1:,3]

In [ ]:
s=a2.astype(float)

In [ ]:
s

array([1000., 1000., 1001., ..., 9959.,  999., 9998.])

In [ ]:
s.sort()